---
# tasks file for apt-over-https

- name: Perform any setup before altering apt repository URLs
  ansible.builtin.include_tasks: setup.yml

- name: Load tasks file with install tasks based on the OS type
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/tasks"

- name: Update the cache using the updated sources
  ansible.builtin.apt:
    force_apt_get: yes
    update_cache: yes
