# Since Ubuntu's official package repositories **do not** support HTTPS
# we cannot convert every URL to use HTTPS instead of HTTP. We must skip
# any URLs that use the official repositories.
- name: Convert any non-official HTTP source URLs to use HTTPS
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '(deb(?:-src)? (?:\[[^\]]+\] )?)http://(?!\S*(?:ubuntu|canonical)\.com)'
    replace: '\1https://'
  loop: "{{ apt_source_files }}"
